spring.application.name=20-SB-Redis-App

spring.data.redis.url=redis-14835.c9.us-east-1-4.ec2.cloud.redislabs.com
spring.data.redis.port=14835
spring.data.redis.username=default
spring.data.redis.password=zwm7JeFjNK0Mb5idZ1WwWnJI4ditBhXc