spring:
  application:
    name: greet
  boot:
    admin:
      client:
        url: http://localhost:1111/
  config:
    import: optional:configserver:http://localhost:2222
server:
  port: 9091
management:
  endpoints:
    web:
      exposure:
        include: 
          - "*"
          - refresh